### ISSUE TITLE
Erro ao criar sala.

### ISSUE THREAD

**Issue by nathan130200** [Rubensigner/emulator#1]
(node:11880) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
		events.js:160
		throw er; // Unhandled 'error' event
			^

	TypeError: Cannot read property 'mission_key' of null
		at parseXMLModel (B:\emulator\dist\app\xmpp\gameroom\gameroomopen.js:74:40)
		at B:\emulator\dist\app\xmpp\gameroom\gameroomopen.js:95:12
		at Query.<anonymous> (B:\emulator\node_modules\mongoose\lib\model.js:3419:16)
		at B:\emulator\node_modules\kareem\index.js:264:21
		at B:\emulator\node_modules\kareem\index.js:127:16
		at _combinedTickCallback (internal/process/next_tick.js:67:7)
		at process._tickCallback (internal/process/next_tick.js:98:9)

	B:\emulator>

**Comment by nathan130200** [comment]
Tive que resetar o database, mas agora voltou a funcionar! 👍  vc é foda.

**Comment by rubensmesquita** [comment]
Não tinha visto seu problema, passei o dia quase todo fora :/ mais pelo menos você conseguiu resolver.

link do forum se quiser saber de outras coisas, http://game-amazing.ga/

**Comment by nathan130200** [comment]
Vlw 👍  E agora pra entrar em algum servidor? Eu fiquei sabendo que precisa de um UDP ou algo do tipo

**Comment by rubensmesquita** [comment]
Você sabe programar com alguma C/C++/C# ?

**Comment by rubensmesquita** [comment]
No caso do UDP e o servidor dedicado, não e possível fazer ela do zero, entra em contato comigo pelo forum, que eu bato um papo com vc pelo chat! a respeito do servidor dedicado.

**Comment by nathan130200** [comment]
ok

**Comment by nathan130200** [comment]
C# +-

**Comment by nathan130200** [comment]
Ah se for de ajuda, muito tempo atras achei isso: http://pastebin.com/XHfYkqP3 o cara q postou isso disse que é a base do udp do warface.

**Comment by rubensmesquita** [comment]
Vai lá estou online!

**Comment by rubensmesquita** [comment]
Esse código ai foi eu quem fiz haha!

**Comment by nathan130200** [comment]
Ah ta kkkk

**Comment by nathan130200** [comment]
O que ele exatamante faz?

**Comment by nathan130200** [comment]
Outra coisa eu dei fork no projeto e to configurando as missões de coop de umas queries que achei pela internet 👍

**Comment by nathan130200** [comment]
Se quiser ajuda com a criação do launcher só chamar. Ah meu nick no fórum me registrei como FRNathan13

**Comment by nathan130200** [comment]
Outra coisa to modificando o app.js (servidor xmpp) pra reconhecer o token.

**Comment by rubensmesquita** [comment]
Isso em produção é legal, mais em desenvolvimento só atrapalha haha.
